project_name: cso-data

# *Data files should live in the ./data folder if not too big, else in SQL.
# This enables versioning of input data (e.g. life tables)
# Don't forget to remove ./data from .gitignore if versioned data files are stored there!